### ISSUE TITLE
Bug on IOS 

### ISSUE THREAD

**Issue by castronu** [mcwebb/angular-sound#1]
Hi,
Thank you for this usefull lib.

I've noticed a problem when executing within IOS. 
I cannot provide any log, sorry (I'm using the simulator, don't have IPhone to debug).

When executed on an IOS device, SoundService.getSound crashes.

Have a nice day,
  Diego

**Comment by mcwebb** [comment]
Hi castronu,
Unfortunately I don't have time at the moment to debug this myself. Is the emulator itself crashing?
You should be able to access the console log even on the emulator through Safari.

**Comment by bobrosoft** [comment]
Same issue. Can you merge https://github.com/mcwebb/AudioContext-MonkeyPatch/pull/1 ? Should fix it.

**Comment by mcwebb** [comment]
Just merged, thanks for the PR.
Can you confirm whether this issue can now be closed?

**Comment by bobrosoft** [comment]
Yes, working now. Thanks!
